name: pcitrue
description: "Pcitrue - a Flutter M3 painting studio."
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  image: ^4.10.1
  path: ^1.9.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
